@echo off
echo ================================
echo ANDROID BUILD FIX FOR LOCAL ENV
echo ================================
echo.

echo Step 1: Installing dependencies...
call npm install
if %ERRORLEVEL% neq 0 (
    echo ERROR: npm install failed
    pause
    exit /b 1
)

echo.
echo Step 2: Cleaning Android build cache...
if exist "android\app\build" rmdir /s /q "android\app\build"
if exist "android\build" rmdir /s /q "android\build"
if exist "android\.gradle" rmdir /s /q "android\.gradle"

echo.
echo Step 3: Creating missing Capacitor plugin directory...
if not exist "android\capacitor-cordova-android-plugins" mkdir "android\capacitor-cordova-android-plugins"
if not exist "android\capacitor-cordova-android-plugins\src\main\java" mkdir "android\capacitor-cordova-android-plugins\src\main\java"
if not exist "android\capacitor-cordova-android-plugins\src\main\res" mkdir "android\capacitor-cordova-android-plugins\src\main\res"

echo.
echo Step 4: Creating cordova.variables.gradle...
echo // DO NOT EDIT THIS FILE! IT IS GENERATED EACH TIME "capacitor update" IS RUN > "android\capacitor-cordova-android-plugins\cordova.variables.gradle"
echo ext { >> "android\capacitor-cordova-android-plugins\cordova.variables.gradle"
echo   cdvMinSdkVersion = project.hasProperty('minSdkVersion') ? rootProject.ext.minSdkVersion : 23 >> "android\capacitor-cordova-android-plugins\cordova.variables.gradle"
echo   // Plugin gradle extensions can append to this to have code run at the end. >> "android\capacitor-cordova-android-plugins\cordova.variables.gradle"
echo   cdvPluginPostBuildExtras = [] >> "android\capacitor-cordova-android-plugins\cordova.variables.gradle"
echo   cordovaConfig = [:] >> "android\capacitor-cordova-android-plugins\cordova.variables.gradle"
echo } >> "android\capacitor-cordova-android-plugins\cordova.variables.gradle"

echo.
echo Step 5: Running Capacitor sync...
call npx cap sync android
if %ERRORLEVEL% neq 0 (
    echo WARNING: Capacitor sync had issues, but continuing...
)

echo.
echo Step 6: Verifying required files exist...
if exist "android\capacitor-cordova-android-plugins\cordova.variables.gradle" (
    echo ✓ cordova.variables.gradle exists
) else (
    echo ✗ cordova.variables.gradle missing - MANUAL CREATION REQUIRED
)

if exist "android\app\google-services.json" (
    echo ✓ google-services.json exists
) else (
    echo ✗ google-services.json missing - FIREBASE CONFIG REQUIRED
)

echo.
echo ================================
echo FIX COMPLETE - READY FOR ANDROID STUDIO
echo ================================
echo.
echo Next steps:
echo 1. Open Android Studio
echo 2. File ^> Open ^> Select the 'android' folder
echo 3. Let Gradle sync complete
echo 4. Build the project
echo.
pause