#!/bin/bash

echo "================================"
echo "ANDROID BUILD FIX FOR LOCAL ENV"
echo "================================"
echo

echo "Step 1: Installing dependencies..."
npm install
if [ $? -ne 0 ]; then
    echo "ERROR: npm install failed"
    exit 1
fi

echo
echo "Step 2: Cleaning Android build cache..."
rm -rf android/app/build
rm -rf android/build
rm -rf android/.gradle

echo
echo "Step 3: Creating missing Capacitor plugin directory..."
mkdir -p android/capacitor-cordova-android-plugins/src/main/java
mkdir -p android/capacitor-cordova-android-plugins/src/main/res

echo
echo "Step 4: Creating cordova.variables.gradle..."
cat > android/capacitor-cordova-android-plugins/cordova.variables.gradle << 'EOF'
// DO NOT EDIT THIS FILE! IT IS GENERATED EACH TIME "capacitor update" IS RUN
ext {
  cdvMinSdkVersion = project.hasProperty('minSdkVersion') ? rootProject.ext.minSdkVersion : 23
  // Plugin gradle extensions can append to this to have code run at the end.
  cdvPluginPostBuildExtras = []
  cordovaConfig = [:]
}
EOF

echo
echo "Step 5: Running Capacitor sync..."
npx cap sync android
if [ $? -ne 0 ]; then
    echo "WARNING: Capacitor sync had issues, but continuing..."
fi

echo
echo "Step 6: Verifying required files exist..."
if [ -f "android/capacitor-cordova-android-plugins/cordova.variables.gradle" ]; then
    echo "✓ cordova.variables.gradle exists"
else
    echo "✗ cordova.variables.gradle missing - MANUAL CREATION REQUIRED"
fi

if [ -f "android/app/google-services.json" ]; then
    echo "✓ google-services.json exists"
else
    echo "✗ google-services.json missing - FIREBASE CONFIG REQUIRED"
fi

echo
echo "================================"
echo "FIX COMPLETE - READY FOR ANDROID STUDIO"
echo "================================"
echo
echo "Next steps:"
echo "1. Open Android Studio"
echo "2. File > Open > Select the 'android' folder"
echo "3. Let Gradle sync complete"
echo "4. Build the project"
echo

chmod +x LOCAL-FIX-COMMANDS.sh