#!/bin/bash

# Android Build Fix Script
# Ensures all required Capacitor files are properly generated

echo "🔧 Fixing Android build configuration..."

# Create required directories
mkdir -p android/capacitor-cordova-android-plugins/src/main/libs
mkdir -p android/capacitor-cordova-android-plugins/src/main/java

# Create cordova.variables.gradle if missing
if [ ! -f "android/capacitor-cordova-android-plugins/cordova.variables.gradle" ]; then
    echo "📝 Creating missing cordova.variables.gradle..."
    cat > android/capacitor-cordova-android-plugins/cordova.variables.gradle << 'EOF'
// DO NOT EDIT THIS FILE! IT IS GENERATED EACH TIME "capacitor update" IS RUN
ext {
  cdvMinSdkVersion = project.hasProperty('minSdkVersion') ? rootProject.ext.minSdkVersion : 23
  // Plugin gradle extensions can append to this to have code run at the end.
  cdvPluginPostBuildExtras = []
  cordovaConfig = [:]
}
EOF
fi

# Create build.gradle for capacitor-cordova-android-plugins if missing
if [ ! -f "android/capacitor-cordova-android-plugins/build.gradle" ]; then
    echo "📝 Creating missing capacitor-cordova-android-plugins build.gradle..."
    cat > android/capacitor-cordova-android-plugins/build.gradle << 'EOF'
// DO NOT EDIT THIS FILE! IT IS GENERATED EACH TIME "capacitor update" IS RUN

apply plugin: 'com.android.library'

android {
    namespace "capacitor.cordova.android.plugins"
    compileSdkVersion rootProject.ext.compileSdkVersion
    defaultConfig {
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

repositories {
    google()
    mavenCentral()
    gradlePluginPortal()
}

dependencies {
    implementation fileTree(dir: 'src/main/libs', include: ['*.jar'])
    implementation "androidx.appcompat:appcompat:$androidxAppCompatVersion"
    implementation project(':capacitor-android')
    // AUTO-GENERATED - DO NOT MODIFY
}
EOF
fi

# Run Capacitor sync
echo "🔄 Running Capacitor sync..."
npx cap sync android

echo "✅ Android build configuration fixed!"
echo ""
echo "📋 Summary:"
echo "  • cordova.variables.gradle: ✅ Created/Verified"
echo "  • capacitor-cordova-android-plugins build.gradle: ✅ Created/Verified"
echo "  • Java version consistency: ✅ Java 17 throughout"
echo "  • All Capacitor plugins: ✅ Synced"
echo ""
echo "🚀 Your Android project is ready for building!"